# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160627_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default=1, upload_to=posts.models.media_upload),
            preserve_default=False,
        ),
    ]
