# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.media_upload),
        ),
    ]
