# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160728_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=posts.models.profile_pic_upload),
        ),
    ]
